version: '3.1'
services:
 portfolio-mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    expose:
      - '27015'
    command: mongod --port 27015
    ports:
      - "27015:27015"
    volumes:
      - ./data:/data/db
